name: app_example
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.2.4
  preferences_annotation: ^2.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.6.0

  flutter_test:
    sdk: flutter

  preferences_generator: ^2.0.0

flutter:
  uses-material-design: true
