include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

formatter:
  page_width: 100

linter:
  rules:
    sort_constructors_first: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false