name: preferences_annotation
description: >- 
  Annotations and interfaces for generating type-safe, boilerplate-free 
  preference management classes.
version: 2.0.1

homepage: https://github.com/puntbyte/preferences_workspace
repository: https://github.com/puntbyte/preferences_workspace/tree/master/packages/preferences_annotation
issue_tracker: https://github.com/puntbyte/preferences_workspace/issues
topics:
  - preferences
  - code-generation
  - annotations
  - configuration

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  meta: ^1.16.0

dev_dependencies:
  test: ^1.26.0
