targets:
  $default:
    builders:
      preferences_generator|preferencesBuilder:
        enabled: true

builders:
  preferences:
    import: "package:preferences_generator/preferences_generator.dart"
    builder_factories: ["preferencesBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|part_cleanup"]