builders:
  # This is the name of the builder that users will configure.
  preferences:
    # Points to the library that contains the `preferencesBuilder` factory.
    import: "package:preferences_generator/preferences_generator.dart"

    # The name of the top-level function in the imported library that creates the builder.
    builder_factories: ["preferences"]

    # Specifies the default file extension for the generated part files.
    build_extensions: {".dart": [".prefs.dart"]}

    # Automatically apply this builder to packages that depend on this one.
    auto_apply: dependents

    # This ensures generated part files are handled correctly by the build system and written
    # directly into the source directory.
    build_to: source
