targets:
  $default:
    builders:
      preferences_generator|preferencesBuilder:
        enabled: true

builders:
  preferences:
    import: "package:preferences_generator/builder.dart"
    builder_factories: ["preferencesBuilder"]
    build_extensions: {".dart": [".pref.dart"]}
    auto_apply: dependents
    build_to: source