name: preferences_generator
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  analyzer: '>=7.0.0 <8.0.0'
  build: ^2.4.2
  build_config: ^1.1.2
  code_builder: ^4.10.1
  dart_style: ^3.1.0
  preferences_annotation: ^1.0.0
  source_gen: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^6.0.0
  #test: ^1.24.0
