name: preferences_generator
description: >-
  A powerful code generator that creates type-safe, boilerplate-free preference modules from simple
  abstract classes, used with `preferences_annotation`.
version: 2.0.2

homepage: https://github.com/puntbyte/preferences_workspace
repository: https://github.com/puntbyte/preferences_workspace/tree/master/packages/preferences_generator
issue_tracker: https://github.com/puntbyte/preferences_workspace/issues
topics:
  - preferences
  - settings
  - storage
  - type-safe

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  analyzer: ^7.6.0
  build: ^3.0.0
  build_config: ^1.1.2
  code_builder: ^4.10.1
  dart_style: ^3.0.0
  preferences_annotation: ^2.0.0
  source_gen: ^3.0.0

dev_dependencies:
  build_runner: ^2.6.0
  build_test: ^3.2.0
  mocktail: ^1.0.4
  test: ^1.26.0
