name: preferences_generator
description: A powerful code generator that creates type-safe, boilerplate-free preference modules 
  from simple abstract classes, used with `preferences_annotation`.
version: 1.1.4
repository: https://github.com/puntbyte/preferences_workspace/tree/master/packages/preferences_generator
issue_tracker: https://github.com/puntbyte/preferences_workspace/issues
topics: [preferences, settings, storage, type-safe]

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  analyzer: '>=7.4.0 <9.0.0'
  build: '>=2.0.0 <4.0.0'
  build_config: ^1.1.2
  code_builder: ^4.10.1
  dart_style: ^3.0.0
  preferences_annotation: ^1.0.1
  source_gen: '>=2.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^6.0.0
  #test: ^1.24.0
