name: console_example
description: A simple console application demonstrating the `preferences_annotation` and 
  `preferences_generator` packages.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.8.1

resolution: workspace

# Add regular dependencies here.
dependencies:
  preferences_annotation: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.15
  preferences_generator: ^0.1.0

  lints: ^6.0.0
  #test: ^1.24.0
