name: console_example
description: A simple console application demonstrating the `preferences_annotation` and 
  `preferences_generator` packages.

publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  preferences_annotation: ^2.0.1

dev_dependencies:
  build_runner: ^2.6.0
  preferences_generator: ^2.0.3
