name: console_example
description: A simple console application demonstrating the `preferences_annotation` and 
  `preferences_generator` packages.

publish_to: none

version: 1.0.0

environment:
  sdk: ^3.8.1

resolution: workspace

# Add regular dependencies here.
dependencies:
  preferences_annotation: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.15
  preferences_generator: ^1.0.0

  lints: ^6.0.0
  #test: ^1.24.0
